# Generated by Django 3.1.4 on 2021-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=122)),
                ('email', models.EmailField(default='', max_length=122)),
                ('post', models.CharField(default='', max_length=122)),
                ('bloodgroup', models.CharField(default='', max_length=122)),
            ],
        ),
    ]
